### ISSUE TITLE
Suggestion - expand the drag window area

### ISSUE THREAD

**Issue by TrigrH** [Battlelogium/Battlelogium#67]
As you can see below the area which you can drag the window is rather small, not a big issue on a typical window but as you are unable to see the area which you are able to drag, it can take multiple attempts to drag a window because you are missing it by only a pixel or two. I suggest that the full bar (highlighted green) is made into the drag area making the experience much less frustrating and more fluid to use.
![](http://img540.imageshack.us/img540/131/Tz1kFo.png)

**Comment by RonnChyran** [comment]
Making the entire area draggable is impossible due to how Battlelogium does this; we use System.Windows.Shell.WindowChrome.SetWindowChrome, what this does is essentially override the visibility and thickness of the normal window chrome. If the width of the bar was increased, the buttons would not be able to be pressed. Without hacking into undocumented APIs this is a limitation of Window's own APIs.

**Comment by TrigrH** [comment]
Would it be possible to have it so when you hover the mouse over that top area the colour changes so its evident that you are able to drag?

**Comment by RonnChyran** [comment]
Theres no event handler for any of that, it really is just a normal window bar. I've essentially just told Windows to render over it instead, only Windows is aware of it. No input can be discerned from that area, everything is intercepted by the compositor.
