### ISSUE TITLE
Automatic focus not working for BF4

### ISSUE THREAD

**Issue by R3B3LCAUSE** [Battlelogium/Battlelogium#75]
When I connect to a server the game window never automatically gains focus despite the option for it being enabled. I have to manually select the BF4 game window. I haven't tested with other games

**Comment by h0tw1r3** [comment]
+1 (windows 10) and BF Hardline also.

**Comment by R3B3LCAUSE** [comment]
Forgot to mention I'm on Win7 x64

**Comment by Jimi-James** [comment]
Same here, Windows 10 x64.

**Comment by RonnChyran** [comment]
Since there will be a new, Battlelog-free client for Battlefield 4 and Battlefield 1 on the way, Battlelogium is no longer supported for these platforms. Battlelogium has never really played well with Frostbite 3+ games due to weird x64 hooking behavior. Perhaps when the new client is released I'll look into a simple Steam wrapper, but there are solutions out there already.

**Comment by Jimi-James** [comment]
Oh. Sorry, I'm new to using Battlelogium. Could you tell me what the new client on its way is called and where those solutions are?
